name: Publish NPM package to GitHub Packages
on:
  release:
    types: [published]
jobs:
  build-and-deploy:
    runs-on: [ self-hosted, linux, X64 ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@mrichforth'
      - run: |
          npm install &&
          npx tsc &&
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}